### ISSUE TITLE
decrypt failed

### ISSUE THREAD

**Issue by guifei0** [yuweiping/jd_seckill_2024#1]
大佬，这个是啥原因导致的呀？麻了 ~
**jd_seckill.py** 第 398 行 response 结果是 604: decrypt failed
resp = self.spider_session.requestWithSign(functionId, body, data)

**Comment by yaoxiaobing** [comment]
大佬 获取getAddressByPin地址显示'no access'

**Comment by ssc7618** [comment]
{'code': '604', 'echo': 'decrypt failed'}  同样的报错

**Comment by yuweiping** [comment]
1. 获取地址有问题的话，检查下jd，地址管理，有没有默认地址。没有权限那应该也是cookie之类的没配对。
2. sign的时候报错我猜测应该是抓包的配置文件参数没配对，检查cookie等信息

**Comment by ssc7618** [comment]
感谢作者，确实是抓包的问题，用functionId=newUserInfo的那条请求中的信息就不报604了，然后functionId=newUserInfo这个请求大小十几k，我用VENT打开直接崩溃了，换了一个抓包软件成功拿到相关信息了。

**Comment by yuweiping** [comment]
> 恭喜 @ssc7618 解决问题，请问你的设备是Android还是iOS？我用iOS的还是没成功，用jdSign.py算出来的sign和抓包的结果不一样emmm

ios和鸿蒙我都没测过。我用的小米做的。

**Comment by yuweiping** [comment]
> > > 恭喜 @ssc7618 解决问题，请问你的设备是Android还是iOS？我用iOS的还是没成功，用jdSign.py算出来的sign和抓包的结果不一样emmm
> > 
> > 
> > ios和鸿蒙我都没测过。我用的小米做的。
> 
> 感谢作者回复，暂时还不清楚问题，可能iOS的跟Android不太一样（BTW，奋飞安全也搞过iOS的，不过我完全不会逆向。。。）。前两天github还有个jd_sign的库（现在已经删了），算出来的结果和本项目引用的那个库算出来的结果是完全一致的。

我认为你的问题不在sign上，sign算法肯定是不分平台的。可能是请求的时候body格式不一致。你抓个ios的包，然后看一下你发送的包差异在哪

**Comment by wxk-cmd** [comment]
大佬，我是鸿蒙的，好像抓下来的包不能用，也是报604: decrypt failed，按照你的使用手册检查了cookie和地址等元素还是不行。不知道是否可以细致一些，就是具体要如何检测cookie之类的配对

**Comment by zy19940510** [comment]
我是报600、{"code":"600","echo":"signature verification failed"}

**Comment by Evexing** [comment]
不行啊，抓newuserinfo也是报604

**Comment by zy19940510** [comment]
可以了，我换安卓手机就行了，实测安卓里面的参数是放params里，但是ios是放body里

**Comment by wxk-cmd** [comment]
> 可以了，我换安卓手机就行了，实测安卓里面的参数是放params里，但是ios是放body里

我想问一下，你是用的vent去抓的包吗，我尝试了安卓、鸿蒙、ios都是报604错误，就是找不到adresslist的错误。我也不知道我是哪里的包抓错了。看能否发一下包的相关信息。

**Comment by Evexing** [comment]
> 可以了，我换安卓手机就行了，实测安卓里面的参数是放params里，但是ios是放body里

请问安卓可以吗？我是鸿蒙不行

**Comment by Evexing** [comment]
有没有抢到的啊，报个喜讯

**Comment by yuweiping** [comment]
> 可以了，我换安卓手机就行了，实测安卓里面的参数是放params里，但是ios是放body里

提个pr吧

**Comment by laijunlinfz** [comment]
> > 可以了，我换安卓手机就行了，实测安卓里面的参数是放params里，但是ios是放body里
> 
> 我想问一下，你是用的vent去抓的包吗，我尝试了安卓、鸿蒙、ios都是报604错误，就是找不到adresslist的错误。我也不知道我是哪里的包抓错了。看能否发一下包的相关信息。

同遇到了这个问题

**Comment by EasyCommanderZ** [comment]
> > > 可以了，我换安卓手机就行了，实测安卓里面的参数是放params里，但是ios是放body里
> > 
> > 
> > 我想问一下，你是用的vent去抓的包吗，我尝试了安卓、鸿蒙、ios都是报604错误，就是找不到adresslist的错误。我也不知道我是哪里的包抓错了。看能否发一下包的相关信息。
> 
> 同遇到了这个问题

报604一个可能的解决方案：使用VNET抓包（安卓端），在我手机上而言，对于所需要的几个参数（除了url外），vnet会在末尾添加一个分号（;），去掉这个分号之后我这边成功了。仅供参考
