### ISSUE TITLE
ERROR: maotai 预约失败:'title'

### ISSUE THREAD

**Issue by gulugulu888** [yuweiping/jd_seckill_2024#9]
运行后报错
ERROR: maotai 预约失败:'title'

请问可能是什么原因？

**Comment by yuweiping** [comment]
resp_json = resp.json()

        try:
            if resp_json['title'] == '您已成功预约，无需重复预约' or resp_json['title'] == '预约成功！':
                logger.info(task['name'] + resp_json['title'])
            else:
                logger.error(task['name'] + ' 预约失败:' + resp_json['content'])
        except Exception as e:
            logger.error(task['name'] + ' 预约失败:' + str(e))

预约返回的内容中没有title字段。
